### ISSUE TITLE
Support prefix for formatNumber

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1067]
The specific use-case is for dollar signs - to ensure they end up within () when in ledger mode and take the desired color when showing red/green.

Not sure if there are other use cases or how / if to generalize further but the $ is important. Would it be clear that `prefix` takes the color and is inside ledger ()?  That is the case with `label`

**Comment by YanaNirvana** [comment]
Just so I understand, when `ledger: true`, we want the `prefix` to be inside ledgers; `()` and take on the appropriate red/green color.

But what happens when `ledger: false`?  I'm assuming that we want `prefix` to be after the negative sign, when a number is negative.  e.g., we wouldn't want `$-13.37`.  Instead we want `-$13.37`?
