### ISSUE TITLE
Grid: Slight selection highlighting delay across pinned columns on odd rows

### ISSUE THREAD

**Issue by pauldelano** [exhi/hoist-react#1079]
1. Create a grid with multiple rows with one or more pinned columns.
2. Click to select rows and notice that on the clicked row the row is highlighted immediately under the cursor but the part of the row on the other side of the pin boundary is highlighted slightly later.
3. Notice that this only happens on odd (1st, 3rd, 5th) rows. It doesn't matter if stripeRows is enabled or not.
From the timing of things it appears that the discrepancy is an early highlight on the odd rows under the mouse cursor.

**Comment by amcclain** [comment]
[Jelly scroll](https://twitter.com/journeydan/status/1118532985735843842) strikes our grid....

**Comment by lbwexler** [comment]
Tom -- Can you take a look at this very weird one?   It makes our grids a little bit "janky".

Very curious to know whether it is reproducible in raw agGrid.  My guess is that as we peel away our code/styling we will pretty quickly find the culprit.

**Comment by TomTirapani** [comment]
The problem was that we applying the selected styling to `:active` rows.

https://github.com/exhi/hoist-react/pull/1087

In a pinned grid, the side of the row that the user clicks on gets the `:active` pseudoclass a frame or 2 before the grid applies `ag-row-selected` to both sides. I think the best solution is to not use the pseudoclass and instead rely on the ag-grid classes.

The reason why it was only happening on odd rows, is that even rows had the following styling which overrode the `:active` style:

https://github.com/exhi/hoist-react/blob/develop/cmp/ag-grid/AgGrid.scss#L81-L92

(Note that, since agGrid counts the headers as a row, the `ag-row-odd` class is actually applied to even rows in the grid. Also note that we are setting background-color for both `--stripe-rows` & `--no-stripe-rows`, which is why toggling stripeRows had no effect)

**Comment by amcclain** [comment]
Interesting - thank you for fixing! Always worth investigating these little things.

I was wondering why we had both the pseudo and selected classes in the rule. It seems like `:active` is mostly intended to be a very momentary thing as a link (or grid row) is clicked to indicate the "click is happening."  I can see why that doesn't sync in time to the non-pinned column. 

I don't have any sense that we need a distinct style there, and we know it wouldn't play well with the pinned grids, so glad we landed here.
