### ISSUE TITLE
Width of jsonInput within RestForm unconstrained

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1083]
Complicated sizing issues with form components strike again:

<img width="485" alt="Screen Shot 2019-04-18 at 6 45 56 PM" src="https://user-images.githubusercontent.com/225806/56400723-3d59c880-620a-11e9-8543-a593f91fa492.png">

**Comment by TomTirapani** [comment]
Fixed in branch: https://github.com/exhi/hoist-react/pull/1085. The problem was due to a combination of container flex-direction being wrong (changed to `row` when inline) and an aspect of flex-box that I wasn't really aware of until now...

By default, flex items have an implicit and "new" `min-width: auto`:

https://www.w3.org/TR/2016/CR-css-flexbox-1-20160301/#min-size-auto

Essentially, this means that by default, flex items won’t shrink below their "minimum content size" (in this case, the width of non-wrapping jsoninput's content). The preferred solution seems to be setting `min-width: 0` to override the implicit `min-width: auto`:

https://dfmcphee.com/flex-items-and-min-width-0/

However, for an unknown reason, in this particular case setting `width: 0` was more useful than `min-width: 0`. Not clear if this is something specific to CodeMirror, but experience was shared by another dev below:

https://github.com/codemirror/CodeMirror/issues/4487#issuecomment-289632883

It took longer to figure this out than it should have, and I must admit I don't feel like I fully grasp what's going on :( It's difficult to find consistent or detailed explanations of this side of flex box.

I'm sure we must have been bitten by this in some form before, and maybe worth investigating further in the context of https://github.com/exhi/hoist-react/issues/859

**Comment by amcclain** [comment]
> I must admit I don't feel like I fully grasp what's going on

That makes two of us!  But if we've resolved the issue I reported and don't see other new ones, we've made progress in the right direction.
