### ISSUE TITLE
Prefs should provide full control over Hoist footer visibility

### ISSUE THREAD

**Issue by YanaNirvana** [exhi/hoist-react#1201]
Currently, if user is an Admin, they will always see the Version bar.  Even if their preferences are set otherwise.

Instead, Admins want to have the option of turning off Version bar to maximize screen space.

Chatting with @lbwexler, we discussed making a method that checks whether users have a pref set.  :)

**Comment by amcclain** [comment]
I had a quick look at our pref code as I remembered there being some complexities in play already around serializing local prefs from the server.  I am sure we could come up with a decent approach, but I also think there would be some tricky bits around reliably determining if a pref had ever been set and keeping that up to date.

And since we haven't needed that yet, I am hesitant to add it for this ticket.

I wonder if a better approach would be to switch to a new pref - `showVersionFooter` or `showHoistFooter` or similar. This could be checked in the same way across all environments. New default in Bootstrap could be true, but we could update the default in the prod database for any app if we wanted to suppress it there.

I don't think we would often do this, but we could of course then also add to the app options to allow users to control.

Thoughts? Thinking this would be more standard / less surprising all around.

**Comment by amcclain** [comment]
@lbwexler re. above

**Comment by YanaNirvana** [comment]
Maybe this is too hacky, but I was thinking of using the xh/userPreferenceAdmin endpoint.  It's the same one that UserPreferencePanel uses.  We can:

1. check if current user is admin via `XH.getUser().isHoistAdmin`
2. if true, we check to see if they have a pref set for themselves via xh/userPreferenceAdmin endpoint
3. a) if they have something set, we respect it, or
  b) if they don't have something set, we use the current logic

Curious what @amcclain and @lbwexler think about this idea?

**Comment by lbwexler** [comment]
Hi:  Definitely a workable idea, but I do think this is little wonky, and an extra request to the server/complexity that would not be worth the value.

**Comment by lbwexler** [comment]
To your idea ATM: My only concern is that if we end up *always* wanting to set the default pref to true in prod, its just extra work for us, that gets us back to where we started -- any user can turn *on* the pref manually in prod, but have to *explicitly* do so.  

I think the main advantage to your approach would be if we wanted to a) not show the footer sometimes in non-prod environments for some users (seems confusing if we turn off, and forget to turn back on in dev, say).  or b)  sometimes default the footer to show for certain apps in prod.

I would vote that we just go back to the previous behavior -- and just somehow make it easier for admins to toggle this preference (in admin app?).  Seems like it was a pretty clear story for us for years!

**Comment by lbwexler** [comment]
another option would be to have the new preference be a tri-state string:
"auto"|"never"|"always"

Would maximize the flexibility, but keep system wide consistency and avoid us from having to change default prefs in different environments  (and remember, we don't have a good preference differ!)

**Comment by YanaNirvana** [comment]
^ I'm on board

**Comment by lbwexler** [comment]
"auto" could also be "byEnvironment", but the main thing is that it is algorithmically determined based on the user type, AND the environment.

new pref could be "xhShowHoistFooter"

**Comment by amcclain** [comment]
Great plan! I think auto gives us the most flexibility for that third option. A note on the pref could clarify. 

Having the option to disable in non prod environments  for demos and screenshots will also be nice.
