### ISSUE TITLE
AgGridModel fails badly with null pointer exception

### ISSUE THREAD

**Issue by TomTirapani** [exhi/hoist-react#1232]
If you try to use the state getter / setter functions in AgGridModel (e.g. `getFilterState`) before the `agApi` / `agColumnApi` are ready, the app will throw badly. This leads to us often having to perform a null check on these apis prior to attempting to use these methods.

Would be nice if these checks could be contained within the methods, to avoid having to use the boilerplate.

**Comment by haynesjm42** [comment]
Was looking at this and am wondering what the expected behavior of our api here should be. Since the AgGridModel does not maintain any state itself, I would consider calling any of the state getter/setter methods before the grid is "ready" a programming error and would expect that we throw an exception in that case. If we just return empty or null state when calling these methods before the grid is ready I think we will just end up with bugs in apps and the api will be more confusing. 

I'm thinking that we can add an `isReady` property to AgGridModel, and throw in each of the state getter/setter methods if called when `isReady` is `false` to make it clear to the app developer that they need to check `isReady` before calling those methods. 

@TomTirapani / @lbwexler / @amcclain - thoughts?

**Comment by lbwexler** [comment]
Ah, I see what you mean.  Sounds like a plan. 

It seems to me that isReady should also be made observable, so that an application can, say, schedule the state to be or written when the grid is ready to take it.
