### ISSUE TITLE
Cannot edit time values for DatePicker with precision 'minutes'

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#1240]
You cannot directly edit the time values for a DateInput with precision 'minutes'.  The picker will immediately close when you try to type text in the time input.

Note that the arrow keys do work, so there is some level of functionality intact there.

From client report.

**Comment by TomTirapani** [comment]
Upon inspection, it turns out this is not a focus related issue as I had initially thought.

We have some logic in place to close the popover upon changing the date. When in 'date' mode, this is nice and saves a click to blur the input. However, when there is time precision, this also means the popover closes when either the date or the time part of the value changes. There doesn't seem to be a way to distinguish between changes to the date and changes to the time in the `onChange` event fired by the `DatePicker`.

I think we have a couple of solutions:

a) Lose the 'auto-close' behaviour when there is time precision, but keep it when there is just a date. Setting a date with time precision will usually require at least 2 steps, and it's problematic to close the popover between each step. This is compounded by the fact that each keyup on the time precision field also updates the date value.
 
b) Remove the 'auto-close' behaviour altogether. This means users will always have to click away / lose focus to hide the popover, but may be easier to reason about.

**Comment by lbwexler** [comment]
Hi Tom!

Thanks for the detailed analysis.  Let's do options a).  No need for a new option "let's just do the right thing", as you describe.
