### ISSUE TITLE
Config editor - input for bool type goes to select then switch

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#1244]
I don't think this is critical at all, but it seems to point to something weird that would be worth resolving.

- In Admin > Config - open add new dialog
- Note that value field is in its default textInput state
- Select bool type
- Value input swaps to a select with true/false options
- Choose an option - value input now becomes a switchInput!

I don't have a strong preference re. the input that's used, but we should choose just one 😄 

Note you can see the same issue in the Add Preference dialog.

**Comment by lbwexler** [comment]
Thanks for finding this.  Was somewhat intentional (see code comment), but agree that this behavior with the control changing its state on the fly when the first value is selected was too crazy

https://github.com/exhi/hoist-react/pull/1269   stabilizes it nicely, I think, but still allows us to favor the switch when possible.

**Comment by amcclain** [comment]
Excellent thanks for cleaning that up - merged!
