### ISSUE TITLE
Add trigger to maximize dialogs

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#173]
Don't look to add them to all, or even by default, but instead reserve for dialogs where it might well be useful - i.e. those detail ones that have big / variable length content.

**Comment by lbwexler** [comment]
Colin -- thanks for this -- so great that we can now work with this code.  

Can we review this together first before submitting to Blueprint?  Want to make sure to get the best possible chances of getting it accepted.

**Comment by lbwexler** [comment]
Colin and I went through this in detail   He is going to make some revisions based on that.  @atm -- please look and offer comments.  If you are ok after that, I think we could submit.

However we also discussed that ultimately we are probably going to want to own dialog ourselves, if nothing else, because of the need to do resizing and draggability.  So really just agreeing with your point above Anselm -- the bokuweb implementation above might be a good starting point/template for our own Hoist Dialog.

So to make a long story short -- I think we can go ahead and submit this completed work, but we should *not* spend a lot more time on it, or convincing Palantir to take it.  We are better off working on our dialog!

**Comment by lbwexler** [comment]
Closing for now --- we will revisit at some point building our own Dialog
