### ISSUE TITLE
All @param decorators should use proper jsdoc

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#210]
Let's go ahead and bomb all remaining @param declarations to use proper jsdoc syntax.

**Comment by amcclain** [comment]
Lee and I discussed this at some length today and are thinking the following (which is of course up for discussion and which we will include in a forthcoming general README on hoist-react):

### Method Params
* Initial focus is on getting plain-old-JS public methods documented in a standard way with `@param` tags, including type information and using the standard JSDoc syntax for config [objects of a particular shape / destructured args](http://usejsdoc.org/tags-param.html#parameters-with-properties).
* OK to use `{Object}` or - more likely - `{*}` where a param could be one of a bunch of different types that would otherwise be annoying to enumerate using the standard `{(string|function|Object|Component...)}` syntax.  That's not to say that the explicit multi-type syntax should be avoided - it could be very helpful in many cases where an arg is of type a or b - but when it gets complicated we'd rather have `{*}` and a well-thought-out plain-English comment that follows.
* Use brackets around optional args (`@param {string} [fancyName]`) 
* Don't encode default values in the doc comments. We strongly suspect this will be too likely to fall out of date, and that we will run into multiple cases where the defaults themselves are complex, depend on other inputs, etc. and can't be simply expressed in this way.

### Component Props
* For React Components, use `propTypes` to document props instead of JSDoc, as this is the React idiom and they provide the typing and optionality flags we're looking for.  Each non-obvious prop should have a simple plain-English description on the line above it in `/** Doc comment about the prop. */` format.

### Apart from params:
* Use of `@returns` optional - encouraged if there is something especially interesting to say about the return, but not sure we need to make this a full standard.  We can feel this one out.
* Ensure our public classes have at least some kind of class-level comment that orients the reader immediately to what they do and what a dev might need to know about them.
* Run through implementation-only classes and decorate with a class-level comment and the `@private` annotation. Class-level doc can also include a sentence or two for our own reference, but does not need to.  Main goal is to make it clear that the entire class is private to Hoist (even more so than a possible `impl` in the package name might do).

**Comment by cnrudd** [comment]
**Edit suggestions to Component Props:**
Add how to specify a default value for a propType (in the doc comment on line above) - do not use `defaultProps`.

**Comment by febbraiod** [comment]
Put this here mostly as a reminder to myself, I've been using two tabs rather than three:

From ATM:
Param docs that need to wrap to multiple lines just get indented three tabs (twelve spaces) from the left margin, so they end up under the "m" in param.

**Comment by amcclain** [comment]
I think it ends up being two tabs from where your cursor lands.  Really not worried about the exact number of spaces (I promise) - just more the idea that you don't need to try to line up the continuation indent with some token in the line before it that might move around. 

I know it all sounds terribly OCD but my hope (and I think it can be true) is that it will be easier to just focus on the content vs. shifting things left and then right again, etc. Of course if we are going insane we can adjust (or have prettier or another robot do it all for us).
