### ISSUE TITLE
LeftRightChooser displays "No Rows to Show" emptyText

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#298]
Why is this not taking our grid default of null / empty string? You can see this via column chooser.

**Comment by febbraiod** [comment]
I have a hunch about this. I think it points to an issue with our empty text handling in general.

I noticed that when I clear my rows from a grid, say for a reload in the new implementation of the loadMask demo in toolbox the empty text on init is hidden as we expect. But on the reset the default empty text return. ('No Row to Show'). I think this is because 'onGridReady' where we hide the text only gets call once, and not on rerender. I'm guessing that with the L/R chooser when you empty out one side that's equivalent to rerendering the grid but not rebuilding it, therefore onGridReady doesn't fire, and the empty text is not hidden.

**Comment by febbraiod** [comment]
Looks like my theory is correct. Spoke to Gil. Going to the hijack this ticket.
