### ISSUE TITLE
AppModel should validate that user has basic access to client UI

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#302]
Currently there is no built-in / buttoned-up way for a client app to lockout a user who does not have permissions. The server will enforce access to data via properly configured Access annotations, but we want a clear and clean way to avoid rendering the client UI and present the user with a standardized lockout panel.

The HoistAppModel decorator defaults several methods to define a basic API around client app auth requirements. I propose we add a new requireRole getter:

```
requireRole: {
  get() {return 'USER'} // exact default TBD
}
```

This can then be checked by `XH` as part of its current bootstrap lifecycle. If the user (once known) does not have the role specified we could go to a new `LoadState.UNAUTHORIZED`.  `AppContainer` would pick that up and a `lockoutPanel`, and its message could include the name of the required role.

An alternative approach would be to return a boolean from a method like `hasBasicAccess` that could perform any arbitrary logic - i.e. look for one of several roles, always return true for open apps, or check some other user metadata. That wouldn't be much additional complexity, although if we wanted the lockout message to be helpful that logic might need to return it as well...

Given the very strong sense we have that there will be some basic role for each JS app, `requireRole` seemed like the simplest and most pragmatic solution for now. (We could always extend it later...)

We could support returning null/empty string for apps that are happy to be completely open, or we could require a special string token if we think that's a safer option.  Relates to the default implementation - if we want to bake in something like 'USER' or if we want to force the issue and ensure this is always specified.

**Comment by lbwexler** [comment]
Colin and I reviewed this:

We decided to use 'null' to signify "no perms".

Also, we decided to 'bootstrap' the hoist services of the app, before showing the lockout panel.  The app itself will not be initialized, or shown, but this allows us to handle impersonation more gracefully (an important feature for testing/ensuring lockouts) as well as tracking lockout activity, etc.   

**On further reflection, I think we should still consider the hasBasicAccess() instead of requireRole()**  Seems like a bit of flexibility that could be useful.  Might allow an app to make use of gates, or environment, or a combination of the above.  these should now be available, now that we are bootstrapping hoist.....
