### ISSUE TITLE
GridModel - rename selection > selectionModel, support selection pass-through

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#306]
I argue it will be an ongoing source of confusion to have `GridModel.selection` not actually be the selection of the grid (i.e. the records), but instead be the SelectionModel instance.  

Even seeing it documented at the top as "immutable" seems weird: "What do you mean, you can't change the selection?"

Suggest we rename the field to `selectionModel` (or `selModel` if too verbose).

Could provide a pass-through getter -  `GridModel.selection` or `GridModel.selectedRecords` - to `selectionModel.records`.  I could certainly imagine that being useful just as it was in Ext. Not sure exactly how a pass-through to `selectionModel.singleRecord` would best be named...

**Comment by lbwexler** [comment]
Working on this now.  I actually liked the name 'selection' for the immutable object better than you do, and it was intentional -- thought the code 'grid.selection.records.forEach()' was pretty clear, and obviated the need for adding pass through getters in the grid.  'grid.selModel.records.forEach()' seemed less clear 

But I see your point.  And it is an instance of a 'StoreSelectionModel'.  Let's use selModel.  I'll also revisit moving the mode (single/multiple) to the model as well as part of this change...

**Comment by amcclain** [comment]
Thanks appreciate it.  I think in general it helps to call out our models for what they are to help reinforce that entire concept as a first-class part of the framework. I realize the pass-through getters add some extra cruft (assuming we want to add them, which I still think we should) but for such a core / common class like GridModel I think it can be well justified.  Happy to discuss anytime of course!
