### ISSUE TITLE
Show specific exception when grails server is unavailable at page load time

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#315]
Right now, we just throw a wonky exception related to the particular ajax call that failed --  the initial authentication.

Would be good to recognize the actual HTTP error from the request (vs. failed auth) and let the user clearly know that the server is unavailable.

**Comment by amcclain** [comment]
Yes thank you for filing!  Especially since in the SSO case we report a "failed to SSO" message which makes it seem very much like something is misconfigured with auth in particular, vs. the entire back-end not being available.  

Would vote for message like "Unable to contact the UI server."  Not sure if there is too much else we can put in there of use......
