### ISSUE TITLE
Investigate Highcharts React wrapper 

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#348]

**Comment by febbraiod** [comment]
The official Highcharts wrapper seems to be doing very little. The source is 44 lines long:

https://github.com/highcharts/highcharts-react/blob/master/src/HighchartsReact.js

Gives you a react cmp that you can pass the following props: 

Highcharts object (so it's not attached to the Window I think)
constructorType (type of chart)
options(config for the chart)
containerProps (props for the div the chart will ultimately be wrapped in)

Manages updating the chart if the options prop changes, puts the chart in a div and attaches a ref to that div to the chart cmp itself. Also destroys the chart itself when the cmp unmounts. That's it.

**Comment by febbraiod** [comment]
Need to look at: https://github.com/kirjs/react-highcharts as well

**Comment by febbraiod** [comment]
Only able to get to this in fits and starts with Client requests taking precedence. However, one thing we should look at is exposing the main HighChart object. Specifically I wanted to adjust the numericSymbols in chart and could not do so as we set the HighChart options in the chart index file: 

Highcharts.setOptions({
    global: {
        useUTC: false
    },
    lang: {
        thousandsSep: ','
    }
});

Not sure if the wrapper is going to make this easier or if we should do this in our implementation but it is a factor to consider.

**Comment by amcclain** [comment]
Hi - for your use case, is it possible to simply import the Highcharts global again in your app file and call setOptions once more?  I am not sure if the call overwrites or layers on additional options, but we could test / find out. Worst case could call in-app with the options we're using now + any additional.

Of course would still like to work to find the most elegant approach to managing HC options, global or otherwise, but if that keeps you moving....

**Comment by lbwexler** [comment]
We'll revisit this at the next time we start producing a large number of charts.
