### ISSUE TITLE
Empty ComboField throws when requireSelection:true and option selected

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#353]
Can reproduce in Toolbox forms tab:

+ Add `requireSelection: true` to the "State" comboField
+ Type a character in empty-to-start field to pop up list of options
+ Choose one - exception thrown to console

**Comment by amcclain** [comment]
In that same example -

+ I defaulted the starting value of state on the model to 'CA' 
+ Form load showing California as intended
+ I am unable to change the value away from California by interacting with the form. 🤕 

I do not know if this is a general issue with the form or if it could be something specific to toolbox.

**Comment by febbraiod** [comment]
This seems to be related to how we are checking if the input is a valid choice, i.e. a selection from the available options. When a user inputs a value (without selecting), we check that it matches the label of a given options, as we don't expect the user to be aware of underlying values. At that time the internalValue of the field is the users input. 

However when the user selects an available option the internal value is then set to the VALUE of the underlying option. Sometimes the value and the label are the same in which case we have no problem. In our particular case the values and labels do not match (e.g. CT and Connecticut). Therefore we revert to the previous external value. Which is why ATM cannot seem to navigate away from California in his example. Not sure about the exception, but that might be because we are reverting to the inital value of 'null'?

Not sure what the solution is yet, but I wanted to leave this here for reference.

**Comment by febbraiod** [comment]
The exception is indeed cause by the initial null, but not because of the reversion (we don't get that far). It's caused because doCommit is triggered onBlur before we get so far as setting the internal value. So two separate problems.

A third issue is when we find an Exact match to the label but 'do nothing' as we 'have a match'. Our internal value matches the label, but that value doesn't necessarily match the underlying value. This is the easiest of the three to fix.
