### ISSUE TITLE
Combofield commits interim entry when pressing enter or clicking to select a suggested choice

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#354]
Can replicate in Toolbox Forms example with "State" combo.

+ This is currently a ComboField with default of `requireSelection:false` 
+ Type e.g. h to show pop-up suggestion of Hawaii
+ Press enter to select that state while carefully looking at the output on the right that shows the values.  
+ You will see "h" flash briefly then "HI".
+ Can see the same when clicking an option.

Field should not commit that intermediate value if you are selecting a displayed option. Realize this is likely tricky due to commit handling on blur/enter but for these fields hoping we can do better if we know the popup is shown.

**Comment by febbraiod** [comment]
This was not fixed along with it's sibling ticket https://github.com/exhi/hoist-react/issues/353.

We think this is occurring because of a call to doCommit via onBlur and/or pressing the enterKey that is followed by a call to onItemSelect. onItemSelect gets us the value we want. It seems that if we are requiringSelection that there shouldn't be any committing done at all via blur or otherwise, unless you have explicitly selected an item from the menu. Although then we have the problem of clearing out garbage input on blur... also what if the user has typed a valid selection and tabs out without explicitly selecting from the menu?
