### ISSUE TITLE
Add support for hierarchical data to Store and GridModel classes (aka TreeGrid)

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#449]

**Comment by amcclain** [comment]
See [relevant ag-Grid docs](https://www.ag-grid.com/javascript-grid-tree-data/#tree-data-mode) regarding supplying hierarchical data - including precomputed aggregations - to the grid component.

We will plan to add support for tree-structured data to a Store class, with corresponding support in GridModel to process / transform this data as needed to feed directly to the Grid. It is likely that a distinct Grid component will _not_ be needed, but instead Grid would be tree-enabled if its corresponding Model was supplied a tree store or otherwise put in that mode.

**Comment by lbwexler** [comment]
This was merged in https://github.com/exhi/hoist-react/commit/7107675e
