### ISSUE TITLE
Update @blueprintjs/select to 3.1.x

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#558]
Attempted in 12.1.0 but unwound due to breaking changes re. our wrapper on the suggest component.

See https://github.com/palantir/blueprint/pull/2747 for the primary pull request - need to understand how to work with the new controlled options around the query.

**Comment by lbwexler** [comment]
Client asking about status of our select field issues.  Would be nice to see if this helps sooner rather than later

**Comment by febbraiod** [comment]
OK will start in on this now

**Comment by febbraiod** [comment]
Was able to get the comboField displaying the proper value and handling the onChange via the query api rather than the inputProps. Still need to test a bit more and make sure the queryComboField works as well. Were there any other known problems?

**Comment by amcclain** [comment]
When I had attempted to update the dropdown fields didn't appear to be working at all - it was pretty obvious.  Looking forwards to reviewing and taking the upgrade / fix!

**Comment by febbraiod** [comment]
Ok great still a few wrinkles to iron out for sure, but wanted to make sure I didn't miss anything we already knew about

**Comment by febbraiod** [comment]
One major wrinkle is that this update breaks our current handling of comboField where requiredSelection == false. Previously if you were to enter a string that did not match any of the available options and hit return we'd use the <enter> to accept the current query/input value as the new 'hoistValue'. Simple. However, in BP's latest version of this control, that <enter> will fire the 'onItemSelect' event regardless of the query string and will pass the value of an internally maintained 'selectedItem'. Which will either be the last item selected or the first item in the list.

This maybe because BP used to clear selectedItem when the user entered input and is now specifically  not doing that as indicated by this test: https://github.com/palantir/blueprint/pull/2747/files#diff-4fd7b63cebf422724b2fffd6692ed7f9L104

**Comment by febbraiod** [comment]
Go the comboBox working when selection is not required by adding the user query as a valid option at the top of our collection so that on pressing enter it is a valid selection and therefore 'onItemSelect' is working for us. I also had to make active item controlled. Progress!

Next hurtle is related to the same BP change in that when we ARE requiring selection from the list, if the query string doesn't match the options we still have a 'selection' in the background that gets commited onItemSelect even if that item has not been selected

**Comment by febbraiod** [comment]
Require selection working again, partially was broken by recent regression, not just the DP update. Spoke to lee about behavior for setting control value to previous value if user has entered a invalid query and tried to commit it. Brought up the point, and it appears this is also prexisting, that once we had a value set on a field if that value is removed we were not reseting to null but to an empty string. This in non-ideal and I will looking into the possibilty of setting to null in such cases instead.

**Comment by febbraiod** [comment]
Work on this is pausing. Lee reviewed and believes our current set up is too complex to begin with and the complexities involved in this update are highlighting this. WIP here:

https://github.com/exhi/hoist-react/tree/upgradeBPSelectPkg

**Comment by amcclain** [comment]
Thanks for the regular updates.  Totally agree that sometimes when things seem to be snowballing it's worth pausing and taking a step back.

Not sure if this was involved at all, but we've discussed flattening/removing the inheritance hierarchy in these classes, which I still support and might help clarify.  We can come right back at it when we're ready!

**Comment by lbwexler** [comment]
Obsolete!  We have adopted new and improved Select controls from react-select.
