### ISSUE TITLE
Test alternate browser support (Edge / Firefox) + Improve display of lockout page

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#603]
We install a [small lockout script](https://github.com/exhi/hoist-react/blob/develop/static/index.html) on our client pages to determine if the user is accessing via a "modern" browser.  Currently this is looking for the presence of `Promise` as well as (interestingly) `Promise.finally`. If that's not found, we provide a minimal message telling them to switch to Chrome.

**(UPDATE:  We have addressed part of this ticket to test Proxy instead of Promise. This is more accurate. But  0ther parts of ticket still relevant (lwexler 11/2018))**

* I don't have an immediate sense of which browsers this does / does not allow. This is a question I would like to be able to answer pretty easily. In particular, do we allow Edge / Firefox? 
  * This could be added as a comment to this lockout file. It doesn't need to be super-specific, but some guidelines for the casual reader would be welcome. (Comment could also address check for `finally`). 
* For the browsers (other than current Chrome) we do allow, I don't believe we've done any real testing. We should do some kind of baseline check here to verify that things are working. We could use a service such as Browserstack if that's helpful, or ensure we have access to suitable Windows machines as needed.
* We deliberately wanted a simple inline check here, and I think that's still appropriate. If we run into issues, however, where we have browsers that are passing this check but not working for other reasons, we might want to consider a library like canIuse.
* I would like to make the styling on the lockout screen slightly nicer.

**Comment by cnrudd** [comment]
When this script was written on May 10 2018, it was tested on: 
Firefox, Safari, Chrome on OS X
Edge, IE11, Chrome, Firefox on windows 10.
IE 11, Chrome on windows 7.

Our Hoist-react apps were also tested at the time and shown to work (landing page loaded and 1 or 2 clicks in) on all of the above mentioned browsers except IE 11 and Edge.

hoist-react code was found to fail on IE 11 and Edge.  It still does.
IE 11 does not support 'promise'.
Edge does support 'promise', but does not support 'promise.finally', hence the two step check.
the 'finally' test is written using bracket notation, because IE 11 can sometimes be used in IE 7 compatibility mode.  IE 7 did not support checking for the presence of object properties that do not exist with dot notation.

Here is browser support for promises.finally documented by [caniuse](https://caniuse.com/#feat=promise-finally) 


A brief comment could be:
// Feature detection to lockout any browser that does not support:
// 'promise' (IE 11, Blackberry Browser, IE Mobile)
// 'promise.finally' (Edge)
// (browser list dated Nov 5 2018)
// See https://caniuse.com/#feat=promise-finally for latest support tables


For more thorough baseline testing, I do think Browserstack is a good idea.  It will me more cost and time efficient.

**Comment by cnrudd** [comment]
Work on this ticket: https://github.com/exhi/hoist-react/issues/781  reveals that our current babel config in hoist-dev-utils  gives promise.finally support to the Edge browser.

Our lockout script is still correct to lockout Edge, because Edge fails on our Toolbox Grids page, (don't know why yet).

Our test for Promise.finally support in our lockout script is no longer the appropriate test, even though it is still effective because it does lockout Edge.

**Comment by cnrudd** [comment]
More work on this ticket: #781 has resulted in an update to the [lockout script](https://github.com/exhi/hoist-react/blob/develop/static/index.html).  It now allows Edge through.  It now has a comment.
  
@amcclain What display improvements did you have in mind?  Some more color?  Font variation?

**Comment by amcclain** [comment]
Catching up here. I think we're good for now, thank you!  

I had tweaked the lockout page slightly, but all the updates above (notably allowing in Edge) are really what matter.
