### ISSUE TITLE
Column.excludeFromChooser property is confusing

### ISSUE THREAD

**Issue by mpeckerman** [exhi/hoist-react#695]
For example, see any TreeColumn.  It just does not appear in the chooser. 

Alternatively, should we have it appear, but not be movable in either direction?

**Comment by amcclain** [comment]
This was confusing when I looked at it.  I made this change - 2dd7b0c0001e835ea70f079a33b437b2def015f8 - @lbwexler can you review?  Any potential problems here - i.e. would we have a treeCol we do want to hide? 

Also, our lock icon was broken all around in column chooser (actually its base component).  Fixed in 329645b18ee86bad791ee543316950dad5081ff7.  🔒😢

**Comment by lbwexler** [comment]
Closing this.  I think Anselm's change addresses it.
