### ISSUE TITLE
@field() annotation should through a warning if used without the parentheses

### ISSUE THREAD

**Issue by cnrudd** [exhi/hoist-react#732]
The @field() annotation must be used with parentheses for it to work as intended.
Specifying the annotation as '@field' without parentheses results in nothing happening.

Most other Hoist-React or Mobx annotations do not need parentheses to work as intended.

We should cause '@field' to throw a console warning reminding the user to add parentheses.

**Comment by amcclain** [comment]
Just for the record, it's a parameterized decorator - one that takes params and returns a curried version of the decorator itself - vs. the others which are not / no longer do. For a while we had some decorators parameterized `()` form - even through we didn't have current params - for consistency, but then we were able to drop that (consistently) for all the class-level decorators. But taking params here is still important.

I am not sure though that there's really any place we could add such a dev-time aid.  It's kind of the equivalent to accidentally calling a function you are passing as a callback instead of passing the function itself. And both the field decorator function and its return are functions, and the point at which it is actually called/applied happens in the babel transpiled version....

**Comment by lbwexler** [comment]
I have a fix for this in https://github.com/exhi/hoist-react/pull/754
