### ISSUE TITLE
Setting sort on LR chooser broken if not sorting by text or group

### ISSUE THREAD

**Issue by febbraiod** [exhi/hoist-react#813]
I am using a chooser in a client app to select or deselect visible series for a chart. The records in the chooser should be sorted by a sort order property on the underlying recs. It appears that, previously, choosers were sorting via the grid store, but now we are using the grid's sortBy. The gridModel warns if it doesn't find a corresponding column to sortBy and the columns in the chooser are hard coded to "[leftTextCol, groupCol]".

**Comment by TomTirapani** [comment]
Discussed this with Don... this doesn't appear to be a regression, but rather something already broken.

The LeftRightChooserModel's sorting is wonky - the constructor offers `leftSortBy` and `rightSortBy`, but the left and right GridModel columns are hardcoded to be `text` and `group`. Since our sorting is actually handled by ag-grid's comparators, the sortBy must be a column on the grid. This means that `text` and `group` are the only valid properties `leftSortBy` and `rightSortBy`.

I propose we change these to boolean props (`leftSorted` | `rightSorted`) that install a 'text' sortBy on the grids. In Don's particular case, the solution would be to *not* use these props and instead sort by sortOrder before setting the data.

**Comment by lbwexler** [comment]
Can we go ahead and do this and prepare a pull request?    Looking to close out tickets that are easily closed.  Thanks.

**Comment by TomTirapani** [comment]
Okay, will prepare something today. Thanks for bringing to attention

**Comment by TomTirapani** [comment]
https://github.com/exhi/hoist-react/pull/994
