### ISSUE TITLE
Re-implement DateInput with an alternate library

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-react#904]
Our current `DateInput` component relies on the Blueprint component for its core implementation. This has several usability issues - most noticeably unwanted opening of the calendar picker as soon as the component is focused.

Several dedicated date picker libraries appear to provide an improved experience all around:
* http://jquense.github.io/react-widgets/api/DateTimePicker/
* https://github.com/Pikaday/Pikaday
* http://react-day-picker.js.org/

**Comment by lbwexler** [comment]
Have a branch in place with the jquense picker

**Comment by febbraiod** [comment]
Lee brought me in on this to help solve what appeared to be a z-index issue in which the 'popup' Calendar appeared to be clipped by its siblings. It turns out that it is being clipped by the control's parent container (a toolbar). The 'popover' is actually being rendered into the parent container and then absolutely positioned above the control. This would be all well and good if the toolbar did not have its overflow property set to 'hidden'.

The problem then becomes should we or should we not set an 'overflow: hidden' property on the toolbar. At least in the Larchmont office, there was a case to be made on both sides. In brief: 

If we do not set 'overflow: hidden' on the toolbar we MAY end up with a bleeding toolbar:

![screen shot 2019-02-08 at 10 42 04 am](https://user-images.githubusercontent.com/15745614/52488705-6c124d80-2b8e-11e9-8477-3de3c90e005f.png)

I emphasize 'MAY' because to achieve this I also had to remove the overflow property from the panel itself. Which actually might mean removing overflow hidden from the toolbar for the sake of the popup/dropdown datepicker is less dangerous than it might seem.

This bleeding is probably a worse look than the clipping, which is the argument for keeping the 'overflow: hidden' on our toolbars:

![screen shot 2019-02-08 at 10 40 55 am](https://user-images.githubusercontent.com/15745614/52488862-ce6b4e00-2b8e-11e9-9b9a-efe36080f625.png)

However, the point was made that if you have either of these problems you've designed yourself a bad toolbar and need to fix either way.

**Comment by amcclain** [comment]
I would have expected the calendar to use a portal, which seems to be the common pattern for several other components we use that render popover-style things, for exactly this reason.

Is that not an option? I would think the docs would cover / address this case.  Even if we were to change toolbar, what about other cases where you would naturally need to escape the bounds of your parent, such as a date picker in a toolbar along the bottom of a dialog?

**Comment by amcclain** [comment]
A quick look at their Github brought up:
https://github.com/jquense/react-widgets/issues/778 and 
https://github.com/jquense/react-widgets/issues/358

This really worries me - it looks like "just stop hiding overflow" is their go-to, but that doesn't jibe with our experience elsewhere and seems really problematic to me.  

I am concerned that this is a blocker for us, although maybe I am not understanding or overstating things. Or if there is a way for us to cause the pop-up to be rendered via a portal somehow on our own (which doesn't seem very likely).  I would think there would be some discussion of this, or might be worth filing an issue to ask.

Right from https://reactjs.org/docs/portals.html:

> A typical use case for portals is when a parent component has an overflow: hidden or z-index style, but you need the child to visually “break out” of its container. For example, dialogs, hovercards, and tooltips.

**Comment by lbwexler** [comment]
I agree, could definitely be a showstopper.

Blueprint wasn't doing all that portal nastiness for fun -- it seems like a
critical thing.....

-Lee

**Comment by amcclain** [comment]
Ah - here is the (open) issue clearly confirming that portals are not currently supported and this is a known limitation: https://github.com/jquense/react-widgets/issues/871 

I do believe we'll need to investigate another component here - unless again I can be convinced that I'm overstating the issue.  That's a real shame as I thought this was a *very* nice implementation of the core control itself.  Maybe that's because they focused on that vs. a draining struggle with portals, popper, focus, etc....  😞

**Comment by lbwexler** [comment]
Restarting this ticket now that we have given up on jquense  :-(

Please note that blueprint itself is relying on 'react-day-picker', so that might not be a great option for although, we might decide that blueprint is somehow the problem.  Blueprint seems to be adding a lot here (including time handling) for better or worse....

**Comment by amcclain** [comment]
Pinging this ticket to prompt a discussion on it this week.  Can also review #925 as a related "date" ticket.

**Comment by lbwexler** [comment]
Tom -- Seemed like this would be a great ticket for you to work on during your trip.

**Comment by lbwexler** [comment]
Tom spent a lot of time looking at this, and we think we can't obviously do better than what we have right now.  We picked up a great change here to prevent automatic pop-up of the picker, which had been a huge pet-peeve of mine, and think with that we can close this:

https://github.com/exhi/hoist-react/commit/8ee0120579d5e191cad883e2964aeb760803f719

👍
