### ISSUE TITLE
JsonInput does not respect 'disabled' prop

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-react#919]

**Comment by shravnk** [comment]
This came up in something else I was working on so took a stab at it. I think that we set CodeMirror's `readonly` prop correctly - the problem is with formatting. Two things I changed [here](https://github.com/exhi/hoist-react/tree/jsonInputDisabled): 

1. Turn off the cursor when disabled (oddly requires `readonly: 'nocursor'`)
2. Use css logic to set the background color when disabled
